# The URL the site will be built for
base_url = "https://oknozor.github.io/toml-bombadil/"
theme = "adidoks"
title = "Toml Bombadil"

compile_sass = true
highlight_code = true
build_search_index = true
taxonomies = [
    { name = "authors", feed = false}
]

[markdown]
highlight_code = true

[extra]
theme_color = "#000"
author = "Paul Delafosse"
github = "https://github.com/oknozor/toml-bombadil"
twitter = "https://twitter.com/AfkTartine"
email = "paul.delafosse@protonmail.com"


[extra.home]
title = " Toml Bombadil"
logo = "logo.png"
lead = "<p> A Dotfile manager written in Rust</p>"
url = "/docs/getting-started/introduction/"
url_button = "Get started"
repo_version = "GitHub v2.2.3"
repo_license = "Open-source MIT License."
repo_url = "https://github.com/oknozor/toml-bombadil"

[[extra.home.list]]
title = "Dotfiles Template"
content = "Inject variables in your dotfiles to manage your dotfile state in one place"
link = "https://observatory.mozilla.org/analyze/doks.netlify.app"

[[extra.home.list]]
title = "GPG encryption"
content = "Encrypt your SSH keys, passwords, corporate configs via GPG and safely commit them to your public dotfile repository"
link = "https://googlechrome.github.io/lighthouse/viewer/?gist=7731347bb8ce999eff7428a8e763b637"

[[extra.home.list]]
title = "Installation hooks"
content = "Live reload your window manager components with pre and post installation hooks"

[[extra.home.list]]
title = "Themes and profiles"
content = "Organize your dotfiles, switch themes and working environment on the fly"
link = "https://googlechrome.github.io/lighthouse/viewer/?gist=7731347bb8ce999eff7428a8e763b637"

[[extra.menu.social]]
name = "GitHub"
pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
url = "https://github.com/oknozor/toml-bombadil"
post = "v2.2.3"
weight = 20

[[extra.menu.social]]
name = "Twitter"
pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
url = "https://twitter.com/AfkTartine"
weight = 10

