background = "#292C3E"
foreground = "#EBEBEB"

text = "#FF261E"
cursor = "#FF261E"
black = "#0d0d0d"
red = "#FF301B"
green = "#A0E521"
yellow = "#FFC620"
blue = "#1BA6FA"
magenta = "#8763B8"
cyan = "#21DEEF"
white = "#EBEBEB"

light_black = "#6D7070"
light_red = "#FF4352"
light_green = "#B8E466"
light_yellow = "#FFD750"
light_blue = "#1BA6FA"
light_magenta = "#A578EA"
light_cyan = "#73FBF1"
light_white = "#FEFEF8"
